# Generated by Django 5.0.7 on 2024-07-23 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200, unique=True)),
                ("custom", models.BooleanField(default=False)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeAccess.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BudgetCategoryAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "budget",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeAccess.budget",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeAccess.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaidItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=200, unique=True)),
                ("item_id", models.CharField(max_length=200, unique=True)),
                ("cursor", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "plaid_account_id",
                    models.CharField(max_length=200, null=True, unique=True),
                ),
                ("balances", models.JSONField(null=True)),
                ("mask", models.CharField(max_length=200, null=True)),
                ("name", models.CharField(max_length=200, null=True)),
                ("official_name", models.CharField(max_length=200, null=True)),
                ("subtype", models.CharField(max_length=200, null=True)),
                ("account_type", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeAccess.plaiditem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=200, unique=True)),
                ("account_id", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "iso_currency_code",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "unofficial_currency_code",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "merchant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateField()),
                ("payment_channel", models.CharField(max_length=50)),
                ("transaction_type", models.CharField(max_length=50)),
                (
                    "plaid_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeAccess.plaiditem",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="budgetcategoryamount",
            constraint=models.UniqueConstraint(
                fields=("budget", "category"), name="unique_budget_category"
            ),
        ),
    ]
