# Generated by Django 5.0.7 on 2024-07-24 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financeAccess", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="merchant_name",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="plaid_item",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="financeAccess.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="location",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pending",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
